"""initial schema

Revision ID: bd34f76cacae
Revises: 
Create Date: 2026-07-03 23:02:27.414879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd34f76cacae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('shark_coin_reward', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('boosters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effect_type', sa.String(length=50), nullable=False),
    sa.Column('effect_value', sa.Float(), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('cost_shark_coins', sa.Integer(), nullable=False),
    sa.Column('max_active', sa.Integer(), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
    sa.Column('usable_in_daily', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('daily_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenge_date', sa.Date(), nullable=False),
    sa.Column('product_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_challenges_challenge_date'), 'daily_challenges', ['challenge_date'], unique=True)
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('outcome_multiplier', sa.Float(), nullable=False),
    sa.Column('market_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rarity', sa.String(length=20), nullable=True),
    sa.Column('humor_level', sa.Integer(), nullable=True),
    sa.Column('realism', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('success','flop','moderate','breakout')", name='ck_product_outcome'),
    sa.CheckConstraint("rarity IN ('common','uncommon','rare','legendary')", name='ck_product_rarity'),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_product_difficulty'),
    sa.CheckConstraint('humor_level BETWEEN 0 AND 5', name='ck_product_humor'),
    sa.CheckConstraint('realism BETWEEN 0 AND 5', name='ck_product_realism'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_difficulty'), 'products', ['difficulty'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_rarity'), 'products', ['rarity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('auth_provider', sa.String(length=20), nullable=True),
    sa.Column('auth_provider_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('game_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starting_balance', sa.BigInteger(), nullable=False),
    sa.Column('ending_balance', sa.BigInteger(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('correct_rounds', sa.Integer(), nullable=True),
    sa.Column('session_score', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.CheckConstraint("mode IN ('classic','streak','daily','head_to_head','speed','themed')", name='ck_session_mode'),
    sa.CheckConstraint("status IN ('active','completed','abandoned')", name='ck_session_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_sessions_mode'), 'game_sessions', ['mode'], unique=False)
    op.create_index(op.f('ix_game_sessions_status'), 'game_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_game_sessions_user_id'), 'game_sessions', ['user_id'], unique=False)
    op.create_table('leaderboard_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leaderboard_type', sa.String(length=20), nullable=False),
    sa.Column('leaderboard_key', sa.String(length=50), nullable=True),
    sa.Column('score', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("leaderboard_type IN ('daily','weekly','all_time','category','mode')", name='ck_leaderboard_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'leaderboard_type', 'leaderboard_key', name='uq_leaderboard_entry')
    )
    op.create_index(op.f('ix_leaderboard_entries_user_id'), 'leaderboard_entries', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=True),
    sa.Column('referral_code', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reward_claimed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','signed_up','played','rewarded')", name='ck_referral_status'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('referred_user_id')
    )
    op.create_index(op.f('ix_referrals_referrer_id'), 'referrals', ['referrer_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('earned_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement')
    )
    op.create_index(op.f('ix_user_achievements_user_id'), 'user_achievements', ['user_id'], unique=False)
    op.create_table('user_boosters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booster_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booster_id'], ['boosters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_boosters_user_id'), 'user_boosters', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('shark_coins', sa.Integer(), nullable=True),
    sa.Column('investor_score', sa.BigInteger(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('total_rounds', sa.Integer(), nullable=True),
    sa.Column('total_correct', sa.Integer(), nullable=True),
    sa.Column('total_profit', sa.BigInteger(), nullable=True),
    sa.Column('biggest_win', sa.BigInteger(), nullable=True),
    sa.Column('biggest_loss', sa.BigInteger(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('best_streak', sa.Integer(), nullable=True),
    sa.Column('play_streak', sa.Integer(), nullable=True),
    sa.Column('last_play_date', sa.Date(), nullable=True),
    sa.Column('persona', sa.String(length=50), nullable=True),
    sa.Column('risk_profile', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('daily_challenge_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['daily_challenges.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'challenge_id', name='uq_daily_participation')
    )
    op.create_table('friend_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('challenger_id', sa.UUID(), nullable=False),
    sa.Column('challenge_code', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('product_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('starting_balance', sa.BigInteger(), nullable=False),
    sa.Column('challenger_score', sa.BigInteger(), nullable=True),
    sa.Column('challenger_session_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_played', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['challenger_session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friend_challenges_challenge_code'), 'friend_challenges', ['challenge_code'], unique=True)
    op.create_table('session_rounds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('investment_amount', sa.BigInteger(), nullable=True),
    sa.Column('booster_used', sa.UUID(), nullable=True),
    sa.Column('outcome_revealed', sa.String(length=20), nullable=True),
    sa.Column('outcome_multiplier', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.BigInteger(), nullable=True),
    sa.Column('score_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('nonce', sa.UUID(), nullable=False),
    sa.CheckConstraint("decision IN ('invest','pass','counter_offer')", name='ck_round_decision'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['game_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_rounds_session_id'), 'session_rounds', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_session_rounds_session_id'), table_name='session_rounds')
    op.drop_table('session_rounds')
    op.drop_index(op.f('ix_friend_challenges_challenge_code'), table_name='friend_challenges')
    op.drop_table('friend_challenges')
    op.drop_table('daily_challenge_participations')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_boosters_user_id'), table_name='user_boosters')
    op.drop_table('user_boosters')
    op.drop_index(op.f('ix_user_achievements_user_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_referrals_referrer_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_leaderboard_entries_user_id'), table_name='leaderboard_entries')
    op.drop_table('leaderboard_entries')
    op.drop_index(op.f('ix_game_sessions_user_id'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_status'), table_name='game_sessions')
    op.drop_index(op.f('ix_game_sessions_mode'), table_name='game_sessions')
    op.drop_table('game_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_rarity'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_difficulty'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_daily_challenges_challenge_date'), table_name='daily_challenges')
    op.drop_table('daily_challenges')
    op.drop_table('boosters')
    op.drop_table('achievements')
    # ### end Alembic commands ###
